import 'dart:convert';

import '../ir/model.dart';
import '../ir/naming.dart';
import 'types.dart';
import 'writer.dart';

const String _header =
    '// GENERATED by tool/generate.dart from tool/spec/mux-openapi.json — do not edit by hand.\n';

final class GeneratedFile {
  const GeneratedFile(this.path, this.content);
  final String path;
  final String content;
}

final class Emitter {
  Emitter(this.ir) {
    for (final c in ir.classes.values) {
      _locations[c.className] = c.kind == ClassKind.params
          ? 'params/${snakeCase(c.className)}.dart'
          : 'models/${snakeCase(c.className)}.dart';
    }
    for (final e in ir.enums.values) {
      _locations[e.enumName] = 'enums/${snakeCase(e.enumName)}.dart';
    }
    for (final u in ir.unions.values) {
      _locations[u.unionName] = 'unions/${snakeCase(u.unionName)}.dart';
    }
    void walk(NamespaceIr namespace) {
      _locations[namespace.className] =
          'resources/${snakeCase(namespace.className)}.dart';
      namespace.children.values.forEach(walk);
    }

    ir.namespaces.values.forEach(walk);
  }

  final GeneratorIr ir;
  final Map<String, String> _locations = {};

  List<GeneratedFile> emitAll() {
    final files = <GeneratedFile>[];
    for (final c in ir.classes.values) {
      files.add(GeneratedFile(
          'lib/src/generated/${_locations[c.className]}', _emitClass(c)));
    }
    for (final e in ir.enums.values) {
      files.add(GeneratedFile(
          'lib/src/generated/${_locations[e.enumName]}', _emitEnum(e)));
    }
    for (final u in ir.unions.values) {
      files.add(GeneratedFile(
          'lib/src/generated/${_locations[u.unionName]}', _emitUnion(u)));
    }
    void walk(NamespaceIr namespace) {
      files.add(GeneratedFile(
          'lib/src/generated/${_locations[namespace.className]}',
          _emitNamespace(namespace)));
      namespace.children.values.forEach(walk);
    }

    ir.namespaces.values.forEach(walk);
    files.add(GeneratedFile(
        'lib/src/generated/webhook_events.g.dart', _emitWebhookEvents()));
    files.add(GeneratedFile('lib/src/generated/generated.dart', _emitBarrel()));
    files.add(GeneratedFile(
        'test/generated/models_decode_test.dart', _emitDecodeTest()));
    files.add(GeneratedFile(
        'test/generated/operations_mock_test.dart', _emitMockTest()));
    files.add(
        GeneratedFile('test/generated/model_examples.json', _emitExamples()));
    files.sort((a, b) => a.path.compareTo(b.path));
    return files;
  }

  String _relative(String fromPath, String toPath) {
    final fromDir = fromPath.contains('/')
        ? fromPath.substring(0, fromPath.lastIndexOf('/'))
        : '';
    final fromParts = fromDir.isEmpty ? <String>[] : fromDir.split('/');
    final toParts = toPath.split('/');
    var common = 0;
    while (common < fromParts.length &&
        common < toParts.length - 1 &&
        fromParts[common] == toParts[common]) {
      common++;
    }
    final up = List.filled(fromParts.length - common, '..');
    return [...up, ...toParts.sublist(common)].join('/');
  }

  String _coreImport(String fromPath, String coreFile) =>
      _relative('generated/$fromPath', 'core/$coreFile');

  List<String> _imports(String fromPath, Set<String> typeNames,
      {Set<String> core = const {},
      Set<String> dart = const {},
      Set<String> extraFiles = const {}}) {
    final lines = <String>{};
    for (final name in dart) {
      lines.add("import 'dart:$name';");
    }
    final packageLines = <String>{};
    for (final file in core) {
      packageLines.add("import '${_coreImport(fromPath, file)}';");
    }
    for (final name in typeNames) {
      final location = _locations[name];
      if (location == null) throw StateError('no generated file for $name');
      if (location == fromPath) continue;
      packageLines.add("import '${_relative(fromPath, location)}';");
    }
    for (final file in extraFiles) {
      if (file == fromPath) continue;
      packageLines.add("import '${_relative(fromPath, file)}';");
    }
    return [
      ...lines.toList()..sort(),
      if (lines.isNotEmpty && packageLines.isNotEmpty) '',
      ...packageLines.toList()..sort()
    ];
  }

  String _emitClass(ClassIr c) {
    final path = _locations[c.className]!;
    final w = DartWriter();
    final referenced = <String>{};
    for (final field in c.fields) {
      referenced.addAll(referencedTypeNames(field.type));
    }
    if (c.superType != null) referenced.add(c.superType!);
    w.line(_header);
    final imports = _imports(path, referenced, core: {
      if (c.fields.isNotEmpty) 'json_reading.dart',
      if (needsDecodeException(c)) 'decode_exception.dart'
    });
    if (imports.isNotEmpty) {
      imports.forEach(w.line);
      w.line();
    }
    final isModel = c.kind == ClassKind.model;
    w.doc(c.docs,
        fallback: isModel
            ? 'The `${c.origin ?? c.className}` object of the Mux API.'
            : 'Parameters for `${c.origin}`.');
    final extendsClause = c.superType == null ? '' : ' extends ${c.superType}';
    w.block('final class ${c.className}$extendsClause {', () {
      w.doc(null,
          fallback: isModel
              ? 'Creates a ${c.className} from already-decoded fields.'
              : 'Creates the parameters.');
      final constructorParams = <String>[];
      for (final field in c.fields) {
        if (field.required) {
          constructorParams.add('required this.${field.dartName},');
        } else if (isModel && field.type is IrList) {
          constructorParams.add('this.${field.dartName} = const [],');
        } else if (isModel && field.type is IrStringMap) {
          constructorParams.add('this.${field.dartName} = const {},');
        } else {
          constructorParams.add('this.${field.dartName},');
        }
      }
      if (isModel) constructorParams.add('this.raw = const {},');
      if (constructorParams.isEmpty) {
        w.line('const ${c.className}();');
      } else {
        w.block(
            'const ${c.className}({', () => constructorParams.forEach(w.line),
            close: '});');
      }
      w.line();
      w.doc(null,
          fallback:
              'Decodes a JSON object into a ${c.className}.${isModel ? '' : ' Fields absent from [json] stay null.'}');
      if (c.fields.isEmpty && !isModel) {
        w.line(
            'factory ${c.className}.fromJson(Map<String, Object?> json) => const ${c.className}();');
      } else {
        w.block(
            'factory ${c.className}.fromJson(Map<String, Object?> json) => ${c.className}(',
            () {
          for (final field in c.fields) {
            w.line(
                '${field.dartName}: ${decodeField(field, c.className, c.kind)},');
          }
          if (isModel) w.line('raw: json,');
        }, close: ');');
      }
      for (final field in c.fields) {
        w.line();
        w.doc(field.docs, fallback: 'The `${field.wireName}` field.');
        if (field.deprecated) {
          w.line(
              '@Deprecated(${dartString(field.deprecationMessage ?? 'Deprecated by Mux.')})');
        }
        w.line('final ${_fieldType(field, c.kind)} ${field.dartName};');
        if (field.dateKind != DateKind.none) {
          w.line();
          w.doc(null,
              fallback:
                  '[${field.dartName}] as an instant, or `null` when absent or unparsable.');
          w.block('DateTime? get ${field.dartName}Date {', () {
            w.line('final value = ${field.dartName};');
            if (field.dateKind == DateKind.unixSecondsString) {
              w.line(
                  'final seconds = value == null ? null : int.tryParse(value);');
              w.line(
                  'return seconds == null ? null : DateTime.fromMillisecondsSinceEpoch(seconds * 1000, isUtc: true);');
            } else {
              w.line('return value == null ? null : DateTime.tryParse(value);');
            }
          });
        }
      }
      if (isModel) {
        w.line();
        w.doc(null,
            fallback:
                'The whole decoded object, for fields not promoted to a property.');
        w.line('final Map<String, Object?> raw;');
      }
      w.line();
      w.doc(null,
          fallback: isModel
              ? 'Encodes the object for a request body, omitting absent fields.'
              : 'Encodes the parameters for the request body, omitting absent fields.');
      if (c.superType != null) w.line('@override');
      if (c.fields.isEmpty) {
        w.line('Map<String, Object?> toJson() => const <String, Object?>{};');
      } else {
        w.block('Map<String, Object?> toJson() => {', () {
          for (final field in c.fields) {
            final key = dartStringLiteral(field.wireName);
            final name = field.dartName;
            if (field.required) {
              w.line('$key: ${encodeValue(field.type, name)},');
            } else if (isModel &&
                (field.type is IrList || field.type is IrStringMap)) {
              w.line(
                  'if ($name.isNotEmpty) $key: ${encodeValue(field.type, name)},');
            } else {
              w.line(
                  'if ($name != null) $key: ${encodeValue(field.type, '$name!')},');
            }
          }
        }, close: '};');
      }
    });
    return w.toString();
  }

  String _fieldType(FieldIr field, ClassKind kind) {
    if (field.type is IrJson) return 'Object?';
    return fieldDartType(field, kind);
  }

  String _emitEnum(EnumIr e) {
    final path = _locations[e.enumName]!;
    final w = DartWriter();
    w.line(_header);
    w.line("import '${_coreImport(path, 'open_enum.dart')}';");
    w.line();
    w.doc(e.docs, fallback: 'The `${e.enumName}` values of the Mux API.');
    w.block('final class ${e.enumName} extends MuxOpenEnum {', () {
      w.line('const ${e.enumName}._(super.value);');
      w.line();
      w.doc(null, fallback: 'Wraps a value this package does not know.');
      w.line('const ${e.enumName}.unknown(super.value);');
      for (final value in e.values) {
        w.line();
        w.doc(null, fallback: 'The `${value.wire}` value.');
        if (value.deprecated) w.line("@Deprecated('Deprecated by Mux.')");
        w.line(
            'static const ${value.dartName} = ${e.enumName}._(${dartString(value.wire)});');
      }
      w.line();
      w.doc(null,
          fallback: 'The values known when this package was generated.');
      w.line(
          'static const values = [${e.values.map((v) => v.dartName).join(', ')}];');
      w.line();
      w.doc(null,
          fallback:
              'Decodes a wire value, preserving one this package does not know.');
      w.block(
          'factory ${e.enumName}.fromWire(String value) => values.firstWhere(',
          () {
        w.line('(known) => known.value == value,');
        w.line('orElse: () => ${e.enumName}.unknown(value),');
      }, close: ');');
      w.line();
      w.line('@override');
      w.line('bool get isKnown => values.contains(this);');
    });
    return w.toString();
  }

  String _emitUnion(UnionIr u) {
    final path = _locations[u.unionName]!;
    final w = DartWriter();
    w.line(_header);
    final referenced = <String>{
      for (final v in u.variants) v.className,
      if (u.superType != null) u.superType!
    };
    final imports = _imports(path, referenced);
    if (imports.isNotEmpty) {
      imports.forEach(w.line);
      w.line();
    }
    w.doc(u.docs,
        fallback:
            'A `${u.unionName}`, one of several shapes told apart by `${u.discriminator}`.');
    final extendsClause = u.superType == null ? '' : ' extends ${u.superType}';
    w.block('abstract base class ${u.unionName}$extendsClause {', () {
      w.doc(null, fallback: 'Creates the base of a ${u.unionName}.');
      w.line('const ${u.unionName}();');
      w.line();
      w.doc(null,
          fallback:
              'Decodes [json] by its `${u.discriminator}`; a value this package does not know decodes to [Unknown${u.unionName}].');
      w.block(
          'factory ${u.unionName}.fromJson(Map<String, Object?> json) => switch (json[${dartStringLiteral(u.discriminator)}]) {',
          () {
        for (final variant in u.variants) {
          w.line(
              '${dartStringLiteral(variant.wireValue)} => ${variant.className}.fromJson(json),');
        }
        w.line('_ => Unknown${u.unionName}(json),');
      }, close: '};');
      w.line();
      w.doc(null, fallback: 'Encodes the object for a request body.');
      if (u.superType != null) w.line('@override');
      w.line('Map<String, Object?> toJson();');
    });
    w.line();
    w.doc(null,
        fallback:
            'A ${u.unionName} whose `${u.discriminator}` this package does not know; [raw] keeps the payload.');
    w.block('final class Unknown${u.unionName} extends ${u.unionName} {', () {
      w.doc(null, fallback: 'Creates the fallback carrying [raw].');
      w.line('const Unknown${u.unionName}(this.raw);');
      w.line();
      w.doc(null, fallback: 'The undecoded payload.');
      w.line('final Map<String, Object?> raw;');
      w.line();
      w.line('@override');
      w.line('Map<String, Object?> toJson() => raw;');
    });
    return w.toString();
  }

  String _emitNamespace(NamespaceIr namespace) {
    final path = _locations[namespace.className]!;
    final w = DartWriter();
    final referenced = <String>{};
    final core = <String>{'client.dart'};
    final dart = <String>{};
    var usesJson = false;
    var usesEnvelope = false;
    for (final op in namespace.operations) {
      if (op.bodyClass != null) referenced.add(op.bodyClass!);
      if (op.pathParams.isNotEmpty) core.add('path_encoding.dart');
      core.add('transport.dart');
      switch (op.response) {
        case UnwrapResponse(:final type):
          referenced.addAll(referencedTypeNames(type));
          usesEnvelope = true;
          usesJson = true;
        case EnvelopeResponse(:final className):
          referenced.add(className);
          usesEnvelope = true;
        case PageResponse(:final itemType):
          referenced.addAll(referencedTypeNames(itemType));
          core.add('page.dart');
          usesEnvelope = true;
        case BytesResponse():
          dart.add('typed_data');
        case VoidResponse():
        case TextResponse():
          break;
      }
    }
    if (usesEnvelope) core.add('envelope.dart');
    if (usesJson) core.add('json_reading.dart');
    final childFiles = {
      for (final child in namespace.children.values)
        _locations[child.className]!
    };
    w.line(_header);
    final imports = _imports(path, referenced,
        core: core, dart: dart, extraFiles: childFiles);
    imports.forEach(w.line);
    w.line();
    final dotted = 'client.${namespace.path.join('.')}';
    w.doc(null, fallback: 'Operations under `$dotted`.');
    w.block('final class ${namespace.className} {', () {
      w.doc(null, fallback: 'Creates the resource backed by [_client].');
      w.line('const ${namespace.className}(this._client);');
      w.line();
      w.line('final MuxClient _client;');
      final children = namespace.children.values.toList()
        ..sort((a, b) => a.path.last.compareTo(b.path.last));
      for (final child in children) {
        w.line();
        w.doc(null, fallback: '`$dotted.${child.path.last}` operations.');
        w.line(
            '${child.className} get ${child.path.last} => ${child.className}(_client);');
      }
      final operations = namespace.operations.toList()
        ..sort((a, b) => a.methodName.compareTo(b.methodName));
      for (final op in operations) {
        w.line();
        _emitOperation(op, w);
      }
    });
    return w.toString();
  }

  void _emitOperation(OperationIr op, DartWriter w) {
    final returnType = _returnType(op.response);
    final positional = <String>[
      for (final p in op.pathParams) '${dartType(p.type)} ${p.dartName}',
      if (op.bodyClass != null) '${op.bodyClass} params',
    ];
    final named = [
      for (final q in op.queryParams) '${dartType(q.type)}? ${q.dartName}'
    ];
    final signature = [
      ...positional,
      if (named.isNotEmpty) '{${named.join(', ')}}',
    ].join(', ');
    final docLines = StringBuffer();
    docLines.writeln('`${op.httpMethod} ${op.pathTemplate}`');
    if (op.docs != null && op.docs!.isNotEmpty) {
      docLines.writeln();
      docLines.writeln(op.docs);
    }
    for (final q in op.queryParams) {
      if (q.docs != null && q.docs!.isNotEmpty) {
        docLines.writeln();
        docLines.writeln('[${q.dartName}]: ${q.docs}');
      }
    }
    w.doc(docLines.toString(),
        fallback: '`${op.httpMethod} ${op.pathTemplate}`');
    if (op.deprecated) {
      w.line(
          '@Deprecated(${dartString(op.deprecationMessage ?? 'Deprecated by Mux.')})');
    }

    final pathExpression = _pathExpression(op);
    final queryLiteral = op.queryParams.isEmpty
        ? null
        : '<String, Object?>{${op.queryParams.map((q) => 'if (${q.dartName} != null) ${dartStringLiteral(_queryKey(q))}: ${q.dartName}').join(', ')}}';
    final host = 'MuxHost.${op.host}';
    final accept = dartStringLiteral(op.accept);

    String call(String method, {String? query, bool withBody = true}) {
      final args = <String>[
        'method: ${dartStringLiteral(op.httpMethod)}',
        'path: $pathExpression',
        if (query != null) 'query: $query',
        if (withBody && op.bodyClass != null) 'body: params.toJson()',
        'host: $host',
        'accept: $accept',
      ];
      return '_client.$method(${args.join(', ')})';
    }

    final response = op.response;
    if (response is PageResponse) {
      final helper = '_${op.methodName}';
      w.line('$returnType ${op.methodName}($signature) => $helper(${[
        for (final p in op.pathParams) p.dartName,
        queryLiteral ?? 'const <String, Object?>{}'
      ].join(', ')});');
      w.line();
      final helperSignature = [
        for (final p in op.pathParams) '${dartType(p.type)} ${p.dartName}',
        'Map<String, Object?> query'
      ].join(', ');
      w.block('$returnType $helper($helperSignature) async {', () {
        w.line('final body = await ${call('requestJson', query: 'query')};');
        final item = _itemClass(response.itemType);
        final pageClass = _pageClass(response.kind);
        final fetch = op.pathParams.isEmpty
            ? helper
            : '(nextQuery) => $helper(${[
                for (final p in op.pathParams) p.dartName,
                'nextQuery'
              ].join(', ')})';
        w.block('return $pageClass<$item>.fromEnvelope(', () {
          w.line('muxEnvelope(body, ${dartStringLiteral(item)}),');
          w.line('itemFromJson: $item.fromJson,');
          w.line('query: query,');
          w.line('fetchPage: $fetch,');
          w.line('objectName: ${dartStringLiteral(item)},');
        }, close: ');');
      });
      return;
    }

    switch (response) {
      case VoidResponse():
        w.block('$returnType ${op.methodName}($signature) async {', () {
          w.line('await ${call('requestJson', query: queryLiteral)};');
        });
      case TextResponse():
        w.line(
            '$returnType ${op.methodName}($signature) => ${call('requestText', query: queryLiteral)};');
      case BytesResponse():
        w.line(
            '$returnType ${op.methodName}($signature) => ${call('requestBytes', query: queryLiteral)};');
      case EnvelopeResponse(:final className):
        w.block('$returnType ${op.methodName}($signature) async {', () {
          w.line(
              'final body = await ${call('requestJson', query: queryLiteral)};');
          w.line(
              'return $className.fromJson(muxEnvelope(body, ${dartStringLiteral(className)}));');
        });
      case UnwrapResponse(:final type):
        w.block('$returnType ${op.methodName}($signature) async {', () {
          w.line(
              'final body = await ${call('requestJson', query: queryLiteral)};');
          w.line('return ${_unwrapExpression(type)};');
        });
      case PageResponse():
        throw StateError('unreachable');
    }
  }

  String _pathExpression(OperationIr op) {
    var template = op.pathTemplate;
    for (final p in op.pathParams) {
      final segment = p.type is IrString
          ? 'muxPathSegment(${p.dartName})'
          : "muxPathSegment('\${${p.dartName}}')";
      template = template.replaceAll('{${p.wireName}}', '\${$segment}');
    }
    return "'$template'";
  }

  String _returnType(ResponseIr response) => switch (response) {
        VoidResponse() => 'Future<void>',
        TextResponse() => 'Future<String>',
        BytesResponse() => 'Future<Uint8List>',
        EnvelopeResponse(:final className) => 'Future<$className>',
        PageResponse(:final kind, :final itemType) =>
          'Future<${_pageClass(kind)}<${_itemClass(itemType)}>>',
        UnwrapResponse(:final type) => 'Future<${_unwrapType(type)}>',
      };

  String _pageClass(PageKind kind) => switch (kind) {
        PageKind.base => 'MuxBasePage',
        PageKind.cursor => 'MuxCursorPage',
        PageKind.withTimeframe => 'MuxPageWithTimeframe',
        PageKind.withTotal => 'MuxPageWithTotal',
      };

  String _itemClass(IrType type) => switch (type) {
        IrRef(:final className) => className,
        IrUnionRef(:final unionName) => unionName,
        _ =>
          throw StateError('page items must be objects, got ${dartType(type)}'),
      };

  String _unwrapType(IrType type) => switch (type) {
        IrRef(:final className) => className,
        IrUnionRef(:final unionName) => unionName,
        IrList(:final element) => 'List<${dartType(element)}>',
        IrJsonMap() => 'Map<String, Object?>?',
        IrJson() => 'Object?',
        IrString() => 'String?',
        _ => throw StateError('unsupported unwrap type ${dartType(type)}'),
      };

  String _unwrapExpression(IrType type) {
    const data = "'data'";
    return switch (type) {
      IrRef(:final className) =>
        '$className.fromJson(muxEnvelope(body, ${dartStringLiteral(className)}).requireObject($data, ${dartStringLiteral(className)}))',
      IrUnionRef(:final unionName) =>
        '$unionName.fromJson(muxEnvelope(body, ${dartStringLiteral(unionName)}).requireObject($data, ${dartStringLiteral(unionName)}))',
      IrList(element: IrRef(:final className)) =>
        "muxEnvelope(body, ${dartStringLiteral(className)}).optObjectList($data, $className.fromJson, objectName: ${dartStringLiteral(className)})",
      IrList(element: IrUnionRef(:final unionName)) =>
        "muxEnvelope(body, ${dartStringLiteral(unionName)}).optObjectList($data, $unionName.fromJson, objectName: ${dartStringLiteral(unionName)})",
      IrList(element: IrString()) =>
        "muxEnvelope(body, 'data').optStringList($data)",
      IrList(element: IrJson()) =>
        "muxEnvelope(body, 'data').optList($data, (element) => element)",
      IrJsonMap() => "muxEnvelope(body, 'data').optObject($data)",
      IrJson() => "muxEnvelope(body, 'data')[$data]",
      IrString() => "muxEnvelope(body, 'data').optString($data)",
      _ => throw StateError('unsupported unwrap type ${dartType(type)}'),
    };
  }

  String _emitWebhookEvents() {
    final w = DartWriter();
    w.line(_header);
    w.line("part of '../webhooks/mux_webhook_event.dart';");
    for (final event in ir.webhooks) {
      w.line();
      w.doc(event.docs, fallback: 'The `${event.eventType}` webhook event.');
      w.block('final class ${event.className} extends MuxWebhookEvent {', () {
        w.doc(null, fallback: 'Creates the event from already-decoded fields.');
        w.block('const ${event.className}({', () {
          w.line('required super.id,');
          w.line('required super.type,');
          w.line('required super.createdAt,');
          w.line('required super.object,');
          w.line('required super.environment,');
          w.line('required super.attempts,');
          w.line('required super.raw,');
          if (event.dataType != null) w.line('this.data,');
        }, close: '});');
        w.line();
        w.doc(null, fallback: 'Decodes a `${event.eventType}` delivery.');
        w.block(
            'factory ${event.className}.fromJson(Map<String, Object?> json) => ${event.className}(',
            () {
          w.line(
              "id: json.requireString('id', ${dartStringLiteral(event.className)}),");
          w.line(
              "type: json.requireString('type', ${dartStringLiteral(event.className)}),");
          w.line("createdAt: json.optString('created_at'),");
          w.line(
              "object: json.optNested('object', MuxWebhookObject.fromJson),");
          w.line(
              "environment: json.optNested('environment', MuxWebhookEnvironment.fromJson),");
          w.line(
              "attempts: json.optObjectList('attempts', MuxWebhookAttempt.fromJson, objectName: ${dartStringLiteral(event.className)}),");
          w.line('raw: json,');
          if (event.dataType != null) {
            w.line('data: ${_decodeWebhookData(event.dataType!)},');
          }
        }, close: ');');
        if (event.dataType != null) {
          w.line();
          w.doc(null, fallback: 'The event payload.');
          w.line('final ${_webhookDataType(event.dataType!)} data;');
        }
      });
    }
    w.line();
    w.doc(null,
        fallback:
            'Decoders by event `type`, generated from the specification.');
    w.block(
        'const Map<String, MuxWebhookEventDecoder> _muxWebhookEventDecoders = {',
        () {
      for (final event in ir.webhooks) {
        w.line(
            '${dartStringLiteral(event.eventType)}: ${event.className}.fromJson,');
      }
    }, close: '};');
    return w.toString();
  }

  String _webhookDataType(IrType type) => switch (type) {
        IrRef(:final className) => '$className?',
        IrUnionRef(:final unionName) => '$unionName?',
        IrJsonMap() => 'Map<String, Object?>?',
        _ =>
          throw StateError('unsupported webhook data type ${dartType(type)}'),
      };

  String _decodeWebhookData(IrType type) => switch (type) {
        IrRef(:final className) =>
          "json.optNested('data', $className.fromJson)",
        IrUnionRef(:final unionName) =>
          "json.optNested('data', $unionName.fromJson)",
        IrJsonMap() => "json.optObject('data')",
        _ =>
          throw StateError('unsupported webhook data type ${dartType(type)}'),
      };

  String _emitBarrel() {
    final w = DartWriter();
    w.line(_header);
    w.doc(null,
        fallback:
            'Every generated model, parameter class, enum, union and resource.');
    w.line('library;');
    w.line();
    final files = _locations.values.toSet().toList()..sort();
    for (final file in files) {
      w.line("export '$file';");
    }
    return w.toString();
  }

  String _emitDecodeTest() {
    final w = DartWriter();
    w.line(_header);
    w.line("import 'dart:convert';");
    w.line("import 'dart:io';");
    w.line();
    w.line("import 'package:mux_api/mux_api.dart';");
    w.line("import 'package:test/test.dart';");
    w.line();
    w.block(
        'final Map<String, Object Function(Map<String, Object?>)> _decoders = {',
        () {
      for (final c in ir.classes.values) {
        w.line('${dartStringLiteral(c.className)}: ${c.className}.fromJson,');
      }
      for (final u in ir.unions.values) {
        w.line('${dartStringLiteral(u.unionName)}: ${u.unionName}.fromJson,');
      }
    }, close: '};');
    w.line();
    w.block('const Map<String, Map<String, Object?>> _minimal = {', () {
      for (final c in ir.classes.values) {
        w.line(
          '${dartStringLiteral(c.className)}: ${_minimalLiteral(c, {
                c.className
              })},',
        );
      }
      for (final u in ir.unions.values) {
        w.line('${dartStringLiteral(u.unionName)}: {},');
      }
    }, close: '};');
    w.line();
    w.block('void main() {', () {
      w.line(
          "final examples = jsonDecode(File('test/generated/model_examples.json').readAsStringSync()) as Map<String, Object?>;");
      w.block('for (final entry in _decoders.entries) {', () {
        w.block("test('\${entry.key} decodes a minimal payload', () {", () {
          w.line('final decoded = entry.value(_minimal[entry.key]!);');
          w.line(
              "expect((decoded as dynamic).toJson(), isA<Map<String, Object?>>());");
        }, close: '});');
        w.block(
            'for (final example in (examples[entry.key] as List<Object?>?) ?? const <Object?>[]) {',
            () {
          w.block("test('\${entry.key} decodes a specification example', () {",
              () {
            w.line(
                'final decoded = entry.value(example as Map<String, Object?>);');
            w.line(
                "expect((decoded as dynamic).toJson(), isA<Map<String, Object?>>());");
          }, close: '});');
        });
      });
    });
    return w.toString();
  }

  String _minimalLiteral(ClassIr c, Set<String> visiting,
      {bool specRequired = false}) {
    final entries = _minimalEntries(c, visiting, specRequired: specRequired);
    return entries.isEmpty
        ? '<String, Object?>{}'
        : '<String, Object?>{${entries.join(', ')}}';
  }

  List<String> _minimalEntries(ClassIr c, Set<String> visiting,
          {required bool specRequired, String? skipWire}) =>
      [
        for (final field in c.fields)
          if (field.wireName != skipWire &&
              (field.required || (specRequired && field.requiredInSpec)))
            '${dartStringLiteral(field.wireName)}: ${_stubValue(field.type, visiting, specRequired: specRequired)}',
      ];

  String _unionStub(UnionIr u, Set<String> visiting) =>
      '<String, Object?>{${_unionEntries(u, visiting).join(', ')}}';

  List<String> _unionEntries(UnionIr u, Set<String> visiting) {
    final variants = u.variants.toList()
      ..sort((a, b) => a.wireValue.compareTo(b.wireValue));
    final variant = variants.first;
    final nestedUnion = ir.unions[variant.className];
    final variantClass = ir.classes[variant.className];
    return [
      '${dartStringLiteral(u.discriminator)}: ${dartStringLiteral(variant.wireValue)}',
      if (nestedUnion != null)
        ..._unionEntries(nestedUnion, visiting)
      else if (variantClass != null && !visiting.contains(variant.className))
        ..._minimalEntries(variantClass, {...visiting, variant.className},
            specRequired: true, skipWire: u.discriminator),
    ];
  }

  String _stubValue(IrType type, Set<String> visiting,
          {bool specRequired = false}) =>
      switch (type) {
        IrString() => "'x'",
        IrInt() => '0',
        IrDouble() => '0.0',
        IrBool() => 'false',
        IrJson() => specRequired ? "'x'" : 'null',
        IrStringMap() => '<String, String>{}',
        IrJsonMap() => '<String, Object?>{}',
        IrList(:final element) => specRequired
            ? '<Object?>[${_stubValue(element, visiting, specRequired: true)}]'
            : '<Object?>[]',
        IrEnumRef(:final enumName) =>
          dartStringLiteral(ir.enums[enumName]!.values.first.wire),
        IrUnionRef(:final unionName) => specRequired
            ? _unionStub(ir.unions[unionName]!, visiting)
            : '<String, Object?>{}',
        IrRef(:final className) => visiting.contains(className)
            ? '<String, Object?>{}'
            : _minimalLiteral(ir.classes[className]!, {...visiting, className},
                specRequired: specRequired),
      };

  String _emitMockTest() {
    final w = DartWriter();
    w.line(_header);
    w.line("@Tags(['mock'])");
    w.line('library;');
    w.line();
    w.line("import 'dart:io';");
    w.line();
    w.line("import 'package:mux_api/mux_api.dart';");
    w.line("import 'package:test/test.dart';");
    w.line();
    w.block('void main() {', () {
      w.line("final host = Platform.environment['MUX_MOCK_HOST'] ?? '';");
      w.block('final client = MuxClient(', () {
        w.line("tokenId: 'mock',");
        w.line("tokenSecret: 'mock',");
        w.line("baseUrl: Uri.parse('http://\$host'),");
        w.line('maxRetries: 0,');
      }, close: ');');
      w.block('setUpAll(() {', () {
        w.block('if (host.isEmpty) {', () {
          w.line(
              "fail('MUX_MOCK_HOST is empty; start tool/mock/run_steady.sh and set MUX_MOCK_HOST=127.0.0.1:4010.');");
        });
      }, close: '});');
      w.line('tearDownAll(client.close);');
      void walk(NamespaceIr namespace) {
        if (namespace.operations.isNotEmpty) {
          final dotted = namespace.path.join('.');
          w.line();
          w.block("group(${dartStringLiteral(dotted)}, () {", () {
            final operations = namespace.operations.toList()
              ..sort((a, b) => a.methodName.compareTo(b.methodName));
            for (final op in operations) {
              final bodyClass = op.bodyClass;
              final args = <String>[
                for (final p in op.pathParams) _paramStub(p),
                if (bodyClass != null)
                  '$bodyClass.fromJson(${_minimalLiteral(ir.classes[bodyClass]!, {
                        bodyClass
                      }, specRequired: true)})',
                for (final q in op.queryParams)
                  '${q.dartName}: ${_paramStub(q)}',
              ];
              w.block("test(${dartStringLiteral(op.methodName)}, () async {",
                  () {
                w.line(
                    'await client.$dotted.${op.methodName}(${args.join(', ')});');
              }, close: '});');
            }
          }, close: '});');
        }
        final children = namespace.children.values.toList()
          ..sort((a, b) => a.path.last.compareTo(b.path.last));
        children.forEach(walk);
      }

      final roots = ir.namespaces.values.toList()
        ..sort((a, b) => a.path.first.compareTo(b.path.first));
      roots.forEach(walk);
    });
    return w.toString();
  }

  String _queryKey(ParamIr param) =>
      param.type is IrList && param.wireName.endsWith('[]')
          ? param.wireName.substring(0, param.wireName.length - 2)
          : param.wireName;

  String _paramStub(ParamIr param) {
    final enumValues = param.enumValues;
    return switch (param.type) {
      IrString() => dartStringLiteral(
          enumValues == null || enumValues.isEmpty ? 'x' : enumValues.first),
      IrInt() => enumValues?.first ?? '1',
      IrDouble() => enumValues?.first ?? '1.0',
      IrBool() => 'true',
      IrList(element: IrString()) => "['x']",
      IrList(element: IrInt()) => '[1]',
      _ => throw StateError(
          'unsupported parameter type for a mock stub: ${dartType(param.type)}'),
    };
  }

  String _emitExamples() {
    final filtered = <String, Object?>{
      for (final entry in ir.examples.entries)
        if (ir.classes.containsKey(entry.key)) entry.key: entry.value,
    };
    final sorted = Map.fromEntries(
        filtered.entries.toList()..sort((a, b) => a.key.compareTo(b.key)));
    return '${const JsonEncoder.withIndent('  ').convert(sorted)}\n';
  }
}
